version: "3.7"

services:
    app:
        image: ghcr.io/eveisesi/krinder:latest
        restart: unless-stopped
        container_name: krinder-app
        env_file: .config/.env
    redis:
        image: redis:6.2.5
        restart: unless-stopped
        container_name: krinder-redis
        env_file: .config/redis/.env
        ports:
            - "55400:6379"
        command: >
            redis-server /etc/redis.conf
        volumes:
            - krinder-cache:/data
            - ./.config/redis/redis.conf:/etc/redis.conf
    mongo:
        image: mongo:latest
        restart: unless-stopped
        container_name: krinder-mongo
        env_file: .config/mongo/.env
        ports:
            - "55410:27017"
        volumes:
            - krinder-mongo:/data/db
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        container_name: krinder-mysql
        env_file: .config/mysql/.env
        ports:
            - "55420:3306"
        volumes:
            - krinder-mysql:/var/lib/mysql
volumes:
    krinder-cache:
    krinder-mongo:
    krinder-mysql:
